In [1]:
import pandas as pd

titanic_data = pd.read_csv("titanic_data.csv")

In [2]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Condition based Filtering

In [3]:
mask = titanic_data.Fare >= 100

fare_100 = titanic_data[mask]

In [10]:
print(fare_100.shape)
fare_100.head()

(53, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [7]:
female_fare_100 = fare_100[fare_100.Sex == "female"]

In [9]:
female_fare_100.shape

(34, 12)

Out of 891 passengers from titanic , 53 were high paying passengers , which includes 65% of female and 35% of male passengers.

In [14]:
# Female Survial Rate

survived_female = titanic_data[
    (titanic_data.Sex == "female") & (titanic_data.Survived == 1)
]
survived_female.shape

(233, 12)

In [18]:
# Survial rate according to Pclass

for i in [1,2,3]:
    temp = titanic_data[
        (titanic_data.Pclass == i) & (titanic_data.Survived == 1)
    ]
    print(f"Survived Passenger in Pclass {i} : {temp.shape[0]}")

Survived Passenger in Pclass 1 : 136
Survived Passenger in Pclass 2 : 87
Survived Passenger in Pclass 3 : 119

In [ ]:
# isna or notna

null_cabin = titanic_data[titanic_data.Cabin.isna()]
null_cabin.shape

(204, 12)

In [24]:
# isna or notna

null_cabin = titanic_data[titanic_data.Cabin.notna()]
null_cabin.shape

(204, 12)

In [31]:
# duplicated

duplicate_name = titanic_data[titanic_data.Name.duplicated()]
duplicate_name

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [33]:
duplicate_ticket = titanic_data[titanic_data.Ticket.duplicated()]
duplicate_ticket

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9000,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
117,118,0,2,"Turpin, Mr. William John Robert",male,29.0,1,0,11668,21.0000,NaN,S
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.2750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [37]:
titanic_data[titanic_data.Name.isin(["Moran, Mr. James"])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [38]:
titanic_data.at[10, "Name"]

'Sandstrom, Miss. Marguerite Rut'

In [39]:
titanic_data.loc[10, "Name"]

'Sandstrom, Miss. Marguerite Rut'

In [2]:
# array Broadcasting
import numpy as np

a = np.array(
    [
        [4,2],
        [5,3]
    ]
)
b = np.array([8,9])

In [3]:
a * b

array([[32, 18],
       [40, 27]])